/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with username and password. Returns a session token valid for 24 hours.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["apitypes.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidates the current session token immediately.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the profile of the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cameras
         * @description Returns all cameras ordered by creation time. Available to all authenticated users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add camera
         * @description Probes the camera for RTSP connectivity, then persists it. Requires admin or owner role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Camera details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["apitypes.CreateCameraRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraResponse"];
                    };
                };
                /** @description Validation error or camera unreachable */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List camera health
         * @description Returns the most recent health status for every known camera. Cameras the monitor has not yet polled are omitted.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraHealthResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get camera
         * @description Returns a single camera by ID. Available to all authenticated users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete camera
         * @description Removes a camera by ID and deregisters it from the media engine. Requires admin or owner role.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update camera settings
         * @description Patches recording configuration for a camera. Only supplied fields are changed. Requires admin or owner.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["apitypes.PatchCameraRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/cameras/{id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get camera health
         * @description Returns the most recent health status for a single camera. 404 if the camera does not exist; 200 with status=unknown if it has not been polled yet.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.CameraHealthResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{id}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get playback URLs for a time range
         * @description Returns URLs to stream every recorded segment for this camera in [start, end) as one continuous fMP4. MediaMTX handles segment stitching transparently.
         */
        get: {
            parameters: {
                query: {
                    /** @description Range start (RFC3339 UTC) */
                    start: string;
                    /** @description Range end (RFC3339 UTC) */
                    end: string;
                };
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.PlaybackURLs"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{id}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recording segments
         * @description Returns completed recording segments for a camera, newest first. Supports optional `from` and `to` query params (RFC3339).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start of time range (RFC3339) */
                    from?: string;
                    /** @description End of time range (RFC3339) */
                    to?: string;
                    /** @description Max results (default 100) */
                    limit?: number;
                    /** @description Pagination offset */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.RecordingListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get stream URLs
         * @description Registers the camera as a MediaMTX source (idempotent) and returns all available live playback URLs: WebRTC/WHEP, HLS, RTSP, RTMP, SRT, all carrying the camera's NATIVE codec. Pass vcodec=h264 to also get a guaranteed-H.264 HLS/WHEP variant (hls_h264 / webrtc_h264), transcoded on demand for WebViews without an HEVC decoder. The H.264 transcode is shared across all viewers, started on first request, and torn down when no one is watching.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Set to 'h264' to also return a guaranteed-H.264 HLS/WHEP variant */
                    vcodec?: "h264";
                };
                header?: never;
                path: {
                    /** @description Camera ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.StreamURLs"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description vcodec=h264 requested but ffmpeg is not installed on the server */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description MediaMTX path registration failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description vcodec=h264 requested but too many concurrent transcodes are running */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/nvr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover cameras on an NVR
         * @description Connects to an NVR via ONVIF, enumerates all camera channels, and returns their RTSP stream URLs. Use the returned rtsp_url values to add cameras via POST /api/cameras. Requires admin or owner role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["apitypes.NVRDiscoverRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.NVRDiscoverResponse"];
                    };
                };
                /** @description Bad request or NVR unreachable */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/nvr/hikvision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover cameras on a Hikvision NVR/DVR via ISAPI
         * @description Connects to a Hikvision device via the ISAPI REST interface (/ISAPI/Streaming/channels), authenticates using HTTP Digest, and returns all enabled camera channels with their RTSP stream URLs. Use this as a fallback when ONVIF is disabled on the device. Requires admin or owner role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["apitypes.NVRDiscoverRequest"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.NVRDiscoverResponse"];
                    };
                };
                /** @description Bad request or device unreachable */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event stream
         * @description Server-sent event stream. Each event is a JSON envelope delivered as SSE. Optional ?pattern= filters by topic (dot-separated glob; default: all events). All current topics are 4-segment: camera.<id>.stream.<state>, camera.<id>.health.changed, recording.<id>.segment.<state>.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Topic glob pattern (default: *.*.*.*) */
                    pattern?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete recording segment
         * @description Removes the recording segment from storage and the database. Requires admin or owner.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Segment ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a recording segment file
         * @description Streams the raw .mp4 (or .ts) segment file. Supports HTTP Range requests for seeking.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Segment ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{id}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get playback URLs for a recording
         * @description Returns URLs the client can use to play a recorded segment. The fMP4 URL points at the supervision-server's authenticated playback proxy.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Segment ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.PlaybackURLs"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns all user accounts. Requires owner or admin role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.UserListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create user
         * @description Creates a new user account. Requires owner or admin. Admin cannot create owner accounts.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["apitypes.CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Username already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Returns a single user. Owner/admin can fetch any user; others can only fetch themselves.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Deletes a user account. Owner only. Cannot delete yourself or other owner accounts.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update user
         * @description Updates role and/or password. Role changes require owner (cannot change own role or an owner's role). Password changes require owner/admin, or the user themselves.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["apitypes.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.UserResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns ok when the server is up and accepting requests.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["apitypes.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "apitypes.CameraHealthResponse": {
            /** @example 1048576 */
            bytes_received?: number;
            /** @example a1b2c3d4e5f6 */
            camera_id?: string;
            /** @example 2026-05-14T10:00:10Z */
            last_checked?: string;
            /** @example connect to 192.168.1.42:554: timeout */
            last_error?: string;
            /** @example 2026-05-14T10:00:00Z */
            last_seen?: string;
            /**
             * @example mediamtx
             * @enum {string}
             */
            source?: "mediamtx" | "rtsp_probe";
            /**
             * @example online
             * @enum {string}
             */
            status?: "unknown" | "online" | "degraded" | "offline";
        };
        "apitypes.CameraResponse": {
            /** @example 2026-05-12T10:00:00Z */
            created_at?: string;
            /** @example generic_rtsp */
            driver_type?: string;
            /** @example true */
            enabled?: boolean;
            /** @example a1b2c3d4e5f6 */
            id?: string;
            /** @example Front Door */
            name?: string;
            /**
             * @description Recording configuration
             * @example true
             */
            record_enabled?: boolean;
            /** @example fmp4 */
            record_format?: string;
            /** @example 720 */
            record_retention_hours?: number;
            /** @example 3600 */
            record_segment_seconds?: number;
            /** @example rtsp://192.168.1.100:554/stream1 */
            rtsp_url?: string;
            /** @example admin */
            username?: string;
        };
        "apitypes.CreateCameraRequest": {
            /** @example generic_rtsp */
            driver_type?: string;
            /** @example Front Door */
            name?: string;
            /** @example password123 */
            password?: string;
            /** @example rtsp://192.168.1.100:554/stream1 */
            rtsp_url?: string;
            /** @example admin */
            username?: string;
        };
        "apitypes.CreateUserRequest": {
            /** @example hunter2 */
            password?: string;
            /** @example viewer */
            role?: string;
            /** @example jsmith */
            username?: string;
        };
        "apitypes.DiscoveredCameraResponse": {
            /** @example Camera 1 */
            name?: string;
            /** @example Profile_1 */
            profile_token?: string;
            /** @example rtsp://192.168.1.100:554/stream1 */
            rtsp_url?: string;
            /** @example admin */
            username?: string;
        };
        "apitypes.ErrorResponse": {
            /** @example invalid credentials */
            error?: string;
        };
        "apitypes.HealthResponse": {
            /** @example ok */
            status?: string;
        };
        "apitypes.LoginRequest": {
            /** @example super-secret */
            password?: string;
            /** @example admin */
            username?: string;
        };
        "apitypes.LoginResponse": {
            /** @example 2026-05-13T10:00:00Z */
            expires_at?: string;
            /** @example a3f5c8d1e2b4... */
            token?: string;
        };
        "apitypes.NVRDiscoverRequest": {
            /** @example password123 */
            password?: string;
            /** @example http://192.168.1.100:80 */
            url?: string;
            /** @example admin */
            username?: string;
        };
        "apitypes.NVRDiscoverResponse": {
            cameras?: components["schemas"]["apitypes.DiscoveredCameraResponse"][];
            /** @example http://192.168.1.100:80 */
            nvr_host?: string;
        };
        "apitypes.PatchCameraRequest": {
            record_enabled?: boolean;
            record_format?: string;
            record_retention_hours?: number;
            record_segment_seconds?: number;
        };
        "apitypes.PlaybackURLs": {
            /** @example b0b392098f5754acf95a144effdd060c */
            camera_id?: string;
            /** @example 300s */
            duration?: string;
            /** @example https://192.168.1.10:8443/api/_playback/get?path=cam-b0b392...&start=2026-05-14T10:30:00Z&duration=300s&format=fmp4 */
            fmp4?: string;
            /**
             * @description FMP4H264 is the same stream re-encoded to H.264 (AVC) by the server.
             *     Use it for clients without an HEVC decoder (Windows WebView2, Linux
             *     WebKitGTK). Requires ffmpeg on the server; returns 501 if unavailable.
             * @example https://192.168.1.10:8443/api/_playback/get?path=cam-b0b392...&start=2026-05-14T10:30:00Z&duration=300s&format=fmp4&vcodec=h264
             */
            fmp4_h264?: string;
            /** @example cam-b0b392098f5754acf95a144effdd060c */
            path?: string;
            /** @example 2026-05-14T10:30:00Z */
            start?: string;
        };
        "apitypes.RecordingListResponse": {
            segments?: components["schemas"]["apitypes.RecordingSegment"][];
            total?: number;
        };
        "apitypes.RecordingSegment": {
            /** @example b0b392098f5754acf95a144effdd060c */
            camera_id?: string;
            /** @example 3600 */
            duration_seconds?: number;
            /** @example 2024-01-15T11:30:00Z */
            ended_at?: string;
            /** @example a1b2c3d4e5f6 */
            id?: string;
            /** @example 524288000 */
            size_bytes?: number;
            /** @example 2024-01-15T10:30:00Z */
            started_at?: string;
            /** @example cam-b0b392.../2024-01-15_10-30-00.mp4 */
            storage_key?: string;
        };
        "apitypes.StreamURLs": {
            /** @example b0b392098f5754acf95a144effdd060c */
            camera_id?: string;
            /**
             * @description H264Path is the MediaMTX path name serving the guaranteed-H.264 variant.
             *     Present only when vcodec=h264 was requested. When the camera is already
             *     H.264 it equals Path (no transcode); otherwise it is "<path>-h264".
             * @example cam-b0b392098f5754acf95a144effdd060c-h264
             */
            h264_path?: string;
            /**
             * @description H264Transcode reports whether a server-side transcode is running to
             *     produce the H.264 variant. false means the camera was already H.264 and
             *     the h264 URLs simply point at the native path (no extra CPU cost).
             *     Present only when vcodec=h264 was requested.
             */
            h264_transcode?: boolean;
            /** @example http://192.168.1.10:8888/cam-b0b392.../index.m3u8 */
            hls?: string;
            /**
             * @description HLSH264 is the HLS (fMP4) playlist whose video is guaranteed H.264 —
             *     playable on every WebView. Present only when vcodec=h264 was requested.
             * @example http://192.168.1.10:8888/cam-b0b392...-h264/index.m3u8
             */
            hls_h264?: string;
            /** @example cam-b0b392098f5754acf95a144effdd060c */
            path?: string;
            /** @example rtmp://192.168.1.10:1935/cam-b0b392... */
            rtmp?: string;
            /** @example rtsp://192.168.1.10:8554/cam-b0b392... */
            rtsp?: string;
            /** @example srt://192.168.1.10:8890?streamid=read:cam-b0b392... */
            srt?: string;
            /** @example http://192.168.1.10:8889/cam-b0b392.../whep */
            webrtc?: string;
            /**
             * @description WebRTCH264 is the WHEP endpoint for the guaranteed-H.264 variant (low
             *     latency). Present only when vcodec=h264 was requested.
             * @example http://192.168.1.10:8889/cam-b0b392...-h264/whep
             */
            webrtc_h264?: string;
        };
        "apitypes.UpdateUserRequest": {
            /** @example newpassword */
            password?: string;
            /** @example admin */
            role?: string;
        };
        "apitypes.UserListResponse": {
            users?: components["schemas"]["apitypes.UserResponse"][];
        };
        "apitypes.UserResponse": {
            /** @example 2026-05-12T10:00:00Z */
            created_at?: string;
            /** @example 550e8400e29b41d4a716446655440000 */
            id?: string;
            /** @example owner */
            role?: string;
            /** @example admin */
            username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description NVR connection details */
        "apitypes.NVRDiscoverRequest": {
            content: {
                "application/json": components["schemas"]["apitypes.NVRDiscoverRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
